Added TemperatureIR, Tilt, DistanceUS
tyrrellsystems/node-red-contrib-tinkerforge pull request #31
Opened 2017-08-10 08:45 UTC by lucas-grab

I added Nodes for the TemperatureIR, Tilt and DistanceUS Bricklets

2017-08-10 10:07 UTC, hardillb requested changes
Mostly looks ok, needs the Copywrite dates updating in all files and look at the tilt sensor output

2017-08-10 10:07 UTC, hardillb commented on bricklets/DistanceUS.html
> +  Copyright 2016 IBM Corp.
You should probably update this to be 2017

2017-08-10 10:07 UTC, hardillb commented on bricklets/Tilt.js
> +					//	if(tiltState === 0) {
Should this be commented out?

2017-08-10 11:15 UTC, lucas-grab commented on bricklets/DistanceUS.html
> +  Copyright 2016 IBM Corp.
done

2017-08-10 11:18 UTC, lucas-grab commented on bricklets/Tilt.js
> +					//	if(tiltState === 0) {
Wasn't sure if the output should be just the numbers or also an explanation.
Changed it to just the numbers, the explanation is in the info section of the node.

2017-08-10 11:32 UTC, hardillb commented on bricklets/Tilt.js
> +                            payload: "tiltState"
You are still just sending the string "tiltState" here not the value

2017-08-10 12:32 UTC, lucas-grab commented on bricklets/Tilt.js
> +                            payload: "tiltState"
You're right. Fixed it.

2017-08-11 07:53 UTC, lucas-grab commented
I also added a Node for the DistanceIR Node.

2017-08-17 15:43 UTC, lucas-grab commented
@hardillb I also added Voltage/Current, Sound Intensity, Linear Poti, Rotary Poti, Barometer, Hall Effect and Piezo Speaker.  Please take a look :)

2017-08-17 16:32 UTC, hardillb commented
Just to be clear, you do have examples of all these sensors you've added to test them with?

2017-08-17 16:32 UTC, hardillb approved these changes

2017-08-18 13:06 UTC, lucas-grab commented
@hardillb Yes, I did test them with the sensors.

2017-08-22 13:18 UTC, lucas-grab commented
@hardillb Added the Line bricklet. Did you have a chance to look at the code?

2017-08-30 10:03 UTC, merged